import { useState, useEffect } from 'react';
import ImageManager from './ImageManager';

const NewsEditor = ({ newsData, onSave }) => {
  const [banners, setBanners] = useState([]);
  const [interval, setInterval] = useState(5000);
  const [showImageManager, setShowImageManager] = useState(false);
  const [editingBannerIndex, setEditingBannerIndex] = useState(null);

  useEffect(() => {
    if (newsData) {
      // Si les bannières sont vides mais qu'on a le système autoLoad, créer des bannières à partir des images existantes
      if (newsData.banners.length === 0 && newsData.autoLoad?.enabled) {
        loadImagesFromFolder();
      } else {
        setBanners(newsData.banners || []);
      }
      setInterval(newsData.interval || 5000);
    }
  }, [newsData]);

  const loadImagesFromFolder = () => {
    // Charger les images existantes depuis le dossier news-images
    const existingImages = ['banniere1.png', 'banniere2.png', 'banniere3.png']; // Images connues
    const autoGeneratedBanners = existingImages.map((imageName, index) => ({
      text: `Actualité ${index + 1}`,
      image: imageName,
      link: '',
      background: '#1a73e8'
    }));
    setBanners(autoGeneratedBanners);
  };

  const addBanner = () => {
    setBanners([...banners, {
      text: '',
      image: '',
      link: '',
      background: '#1a73e8'
    }]);
  };

  const updateBanner = (index, field, value) => {
    const newBanners = [...banners];
    newBanners[index] = { ...newBanners[index], [field]: value };
    setBanners(newBanners);
  };

  const deleteBanner = (index) => {
    if (confirm('Supprimer cette bannière ?')) {
      setBanners(banners.filter((_, i) => i !== index));
    }
  };

  const moveBanner = (index, direction) => {
    const newBanners = [...banners];
    const targetIndex = direction === 'up' ? index - 1 : index + 1;
    
    if (targetIndex >= 0 && targetIndex < banners.length) {
      [newBanners[index], newBanners[targetIndex]] = [newBanners[targetIndex], newBanners[index]];
      setBanners(newBanners);
    }
  };

  const handleSave = () => {
    const newsConfig = {
      banners,
      interval: parseInt(interval)
    };
    onSave(newsConfig);
    alert('Actualités sauvegardées avec succès !');
  };

  const selectImage = (imageName) => {
    if (editingBannerIndex !== null) {
      updateBanner(editingBannerIndex, 'image', imageName);
      setShowImageManager(false);
      setEditingBannerIndex(null);
    }
  };

  return (
    <div>
      <div style={{ 
        display: 'flex', 
        justifyContent: 'space-between', 
        alignItems: 'center', 
        marginBottom: '2rem' 
      }}>
        <h2>
          <i className="fa-solid fa-newspaper"></i> Gestion des Actualités
        </h2>
        <button onClick={handleSave} className="btn btn-primary">
          <i className="fa-solid fa-save"></i> Sauvegarder
        </button>
      </div>

      {/* Configuration générale */}
      <div style={{ 
        background: 'rgba(255,255,255,0.05)', 
        borderRadius: '10px', 
        padding: '1.5rem', 
        marginBottom: '2rem' 
      }}>
        <h3 style={{ marginBottom: '1rem' }}>
          <i className="fa-solid fa-cog"></i> Configuration
        </h3>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <label style={{ fontWeight: 'bold' }}>Intervalle de rotation (ms):</label>
          <input
            type="number"
            value={interval}
            onChange={(e) => setInterval(e.target.value)}
            style={{
              padding: '0.5rem',
              borderRadius: '5px',
              border: '1px solid rgba(255,255,255,0.3)',
              background: 'rgba(255,255,255,0.1)',
              color: 'white',
              width: '120px'
            }}
            min="1000"
            step="500"
          />
          <span style={{ opacity: 0.7, fontSize: '0.9rem' }}>
            (recommandé: 5000ms = 5 secondes)
          </span>
        </div>
      </div>

      {/* Gestionnaire d'images */}
      <div style={{ marginBottom: '2rem' }}>
        <button
          onClick={() => setShowImageManager(!showImageManager)}
          className="btn btn-ghost"
          style={{ marginBottom: '1rem' }}
        >
          <i className="fa-solid fa-images"></i>
          {showImageManager ? 'Masquer' : 'Afficher'} le gestionnaire d'images
        </button>
        
        {showImageManager && (
          <ImageManager 
            folder="news-images" 
            onImageSelect={selectImage}
          />
        )}
      </div>

      {/* Liste des bannières */}
      <div style={{ 
        background: 'rgba(255,255,255,0.05)', 
        borderRadius: '10px', 
        padding: '1.5rem' 
      }}>
        <div style={{ 
          display: 'flex', 
          justifyContent: 'space-between', 
          alignItems: 'center', 
          marginBottom: '1.5rem' 
        }}>
          <h3>
            <i className="fa-solid fa-list"></i> Bannières d'actualités ({banners.length})
          </h3>
          <button onClick={addBanner} className="btn btn-primary">
            <i className="fa-solid fa-plus"></i> Ajouter une bannière
          </button>
        </div>

        {banners.length === 0 && (
          <div style={{ 
            textAlign: 'center', 
            padding: '3rem', 
            opacity: 0.6, 
            fontStyle: 'italic' 
          }}>
            <i className="fa-solid fa-newspaper" style={{ fontSize: '3rem', marginBottom: '1rem' }}></i>
            <p>Aucune bannière d'actualité. Commencez par en ajouter une !</p>
          </div>
        )}

        {banners.map((banner, index) => (
          <div 
            key={index}
            style={{
              background: 'rgba(255,255,255,0.1)',
              borderRadius: '10px',
              padding: '1.5rem',
              marginBottom: '1rem',
              border: '1px solid rgba(255,255,255,0.2)'
            }}
          >
            <div style={{ 
              display: 'flex', 
              justifyContent: 'space-between', 
              alignItems: 'center', 
              marginBottom: '1rem' 
            }}>
              <h4 style={{ margin: 0 }}>
                <i className="fa-solid fa-newspaper"></i> Bannière #{index + 1}
              </h4>
              <div style={{ display: 'flex', gap: '0.5rem' }}>
                <button
                  onClick={() => moveBanner(index, 'up')}
                  disabled={index === 0}
                  className="btn btn-ghost"
                  style={{ padding: '0.25rem 0.5rem' }}
                >
                  <i className="fa-solid fa-arrow-up"></i>
                </button>
                <button
                  onClick={() => moveBanner(index, 'down')}
                  disabled={index === banners.length - 1}
                  className="btn btn-ghost"
                  style={{ padding: '0.25rem 0.5rem' }}
                >
                  <i className="fa-solid fa-arrow-down"></i>
                </button>
                <button
                  onClick={() => deleteBanner(index)}
                  style={{
                    background: 'rgba(220, 53, 69, 0.2)',
                    border: '1px solid rgba(220, 53, 69, 0.4)',
                    color: '#ff6b7a',
                    borderRadius: '4px',
                    padding: '0.25rem 0.5rem',
                    cursor: 'pointer'
                  }}
                >
                  <i className="fa-solid fa-trash"></i>
                </button>
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1rem' }}>
              <div>
                <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 'bold' }}>
                  <i className="fa-solid fa-text-width"></i> Texte de la bannière:
                </label>
                <input
                  type="text"
                  value={banner.text}
                  onChange={(e) => updateBanner(index, 'text', e.target.value)}
                  placeholder="Ex: Nouvelle mise à jour disponible !"
                  style={{
                    width: '100%',
                    padding: '0.75rem',
                    borderRadius: '5px',
                    border: '1px solid rgba(255,255,255,0.3)',
                    background: 'rgba(255,255,255,0.1)',
                    color: 'white'
                  }}
                />
              </div>

              <div>
                <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 'bold' }}>
                  <i className="fa-solid fa-link"></i> Lien (optionnel):
                </label>
                <input
                  type="url"
                  value={banner.link}
                  onChange={(e) => updateBanner(index, 'link', e.target.value)}
                  placeholder="https://exemple.com"
                  style={{
                    width: '100%',
                    padding: '0.75rem',
                    borderRadius: '5px',
                    border: '1px solid rgba(255,255,255,0.3)',
                    background: 'rgba(255,255,255,0.1)',
                    color: 'white'
                  }}
                />
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr auto auto', gap: '1rem', alignItems: 'end' }}>
              <div>
                <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 'bold' }}>
                  <i className="fa-solid fa-image"></i> Image:
                </label>
                <input
                  type="text"
                  value={banner.image}
                  onChange={(e) => updateBanner(index, 'image', e.target.value)}
                  placeholder="nom-image.jpg"
                  style={{
                    width: '100%',
                    padding: '0.75rem',
                    borderRadius: '5px',
                    border: '1px solid rgba(255,255,255,0.3)',
                    background: 'rgba(255,255,255,0.1)',
                    color: 'white'
                  }}
                />
              </div>

              <button
                onClick={() => {
                  setEditingBannerIndex(index);
                  setShowImageManager(true);
                }}
                className="btn btn-ghost"
              >
                <i className="fa-solid fa-folder-open"></i> Choisir
              </button>

              <div>
                <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 'bold' }}>
                  <i className="fa-solid fa-palette"></i> Couleur:
                </label>
                <input
                  type="color"
                  value={banner.background}
                  onChange={(e) => updateBanner(index, 'background', e.target.value)}
                  style={{
                    width: '60px',
                    height: '40px',
                    borderRadius: '5px',
                    border: '1px solid rgba(255,255,255,0.3)',
                    background: 'none',
                    cursor: 'pointer'
                  }}
                />
              </div>
            </div>

            {/* Aperçu */}
            {banner.text && (
              <div style={{ marginTop: '1rem' }}>
                <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 'bold' }}>
                  <i className="fa-solid fa-eye"></i> Aperçu:
                </label>
                <div style={{
                  background: banner.background,
                  color: 'white',
                  padding: '1rem',
                  borderRadius: '5px',
                  textAlign: 'center',
                  border: '1px solid rgba(255,255,255,0.2)'
                }}>
                  {banner.text}
                  {banner.image && (
                    <div style={{ 
                      marginTop: '0.5rem', 
                      fontSize: '0.8rem', 
                      opacity: 0.8 
                    }}>
                      📷 {banner.image}
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export default NewsEditor;